//! Registry implementation.
//!
//! Public entry points are thin: they perform authentication, then delegate to
//! private free functions that take `&Env`. Keeping the logic out of the trait
//! impl means it can be unit-tested directly and composed (e.g. `is_authorized`
//! is reused by `is_authorized_for_corridor`) without re-entering the public
//! ABI and its auth checks.

use soroban_sdk::{contractimpl, token, Address, Env, Symbol, Vec};

use crate::errors::AgentRegistryError;
use crate::events;
use crate::storage;
use crate::types::{Agent, AgentStatus, RegionConfig, RegistryStats};
// `AgentRegistryArgs` and `AgentRegistryClient` are generated by `#[contract]`
// in the crate root; the `#[contractimpl]` macro below refers to them, so they
// have to be in scope inside this module too.
use crate::{AgentRegistry, AgentRegistryArgs, AgentRegistryClient, AgentRegistryInterface};

/* ------------------------------------------------------------------ */
/* internal helpers                                                    */
/* ------------------------------------------------------------------ */

fn require_admin(env: &Env) -> Result<Address, AgentRegistryError> {
    let admin = storage::get_admin(env)?;
    admin.require_auth();
    Ok(admin)
}

fn load_agent(env: &Env, agent: &Address) -> Result<Agent, AgentRegistryError> {
    storage::get_agent(env, agent).ok_or(AgentRegistryError::AgentNotRegistered)
}

fn load_region(env: &Env, region_id: &Symbol) -> Result<RegionConfig, AgentRegistryError> {
    storage::get_region(env, region_id).ok_or(AgentRegistryError::UnknownRegion)
}

fn money_out(
    env: &Env,
    token: &Address,
    to: &Address,
    amount: i128,
) -> Result<(), AgentRegistryError> {
    if amount <= 0 {
        return Err(AgentRegistryError::InvalidAmount);
    }
    token::Client::new(env, token).transfer(&env.current_contract_address(), to, &amount);
    Ok(())
}

/// Count agents currently allowed to settle in a region. Used to enforce the
/// per-region cap at authorization time.
fn count_authorized(env: &Env, region_id: &Symbol) -> u32 {
    let mut count = 0u32;
    for address in storage::region_agents(env, region_id).iter() {
        if let Some(record) = storage::get_agent(env, &address) {
            if record.status == AgentStatus::Authorized {
                count = count.saturating_add(1);
            }
        }
    }
    count
}

fn is_authorized_in(env: &Env, agent: &Address, region_id: &Symbol) -> bool {
    match storage::get_agent(env, agent) {
        Some(record) => {
            let region_active = storage::get_region(env, region_id).is_some_and(|c| c.active);
            record.status.can_settle() && region_active && &record.region_id == region_id
        }
        None => false,
    }
}

/// Apply a lifecycle transition, keeping the `authorized_agents` counter and the
/// event stream consistent. Returns the state we came from.
fn apply_transition(
    env: &Env,
    record: &mut Agent,
    to: AgentStatus,
    reason: &Symbol,
) -> AgentStatus {
    let from = record.status;
    record.status = to;
    record.updated_at = env.ledger().timestamp();
    storage::set_agent(env, record);

    let mut stats = storage::get_stats(env);
    if from == AgentStatus::Authorized && to != AgentStatus::Authorized {
        stats.authorized_agents = stats.authorized_agents.saturating_sub(1);
    } else if from != AgentStatus::Authorized && to == AgentStatus::Authorized {
        stats.authorized_agents = stats.authorized_agents.saturating_add(1);
    }
    storage::set_stats(env, &stats);

    events::agent_status_changed(env, &record.address, &record.region_id, from, to, reason);
    from
}

/* ------------------------------------------------------------------ */
/* contract                                                            */
/* ------------------------------------------------------------------ */

#[contractimpl]
impl AgentRegistryInterface for AgentRegistry {
    fn initialize(
        env: Env,
        admin: Address,
        bond_token: Address,
        treasury: Address,
    ) -> Result<(), AgentRegistryError> {
        if storage::has_admin(&env) {
            return Err(AgentRegistryError::AlreadyInitialized);
        }
        admin.require_auth();

        storage::set_admin(&env, &admin);
        storage::set_bond_token(&env, &bond_token);
        storage::set_treasury(&env, &treasury);
        storage::set_stats(&env, &RegistryStats::default());
        storage::bump_instance(&env);
        Ok(())
    }

    fn set_admin(env: Env, new_admin: Address) -> Result<(), AgentRegistryError> {
        let previous = require_admin(&env)?;
        storage::set_admin(&env, &new_admin);
        storage::bump_instance(&env);
        events::admin_changed(&env, &previous, &new_admin);
        Ok(())
    }

    fn set_treasury(env: Env, treasury: Address) -> Result<(), AgentRegistryError> {
        require_admin(&env)?;
        storage::set_treasury(&env, &treasury);
        storage::bump_instance(&env);
        Ok(())
    }

    fn add_region(
        env: Env,
        region_id: Symbol,
        min_bond: i128,
        max_agents: u32,
    ) -> Result<(), AgentRegistryError> {
        require_admin(&env)?;
        if min_bond < 0 {
            return Err(AgentRegistryError::InvalidAmount);
        }
        if storage::get_region(&env, &region_id).is_some() {
            return Err(AgentRegistryError::RegionAlreadyExists);
        }

        storage::set_region(
            &env,
            &RegionConfig {
                region_id: region_id.clone(),
                min_bond,
                max_agents,
                active: true,
            },
        );
        storage::push_region(&env, &region_id);
        storage::bump_instance(&env);
        events::region_configured(&env, &region_id, min_bond, true);
        Ok(())
    }

    fn set_min_bond(env: Env, region_id: Symbol, min_bond: i128) -> Result<(), AgentRegistryError> {
        require_admin(&env)?;
        if min_bond < 0 {
            return Err(AgentRegistryError::InvalidAmount);
        }
        let mut region = load_region(&env, &region_id)?;
        region.min_bond = min_bond;
        storage::set_region(&env, &region);
        storage::bump_instance(&env);
        events::region_configured(&env, &region_id, min_bond, region.active);
        Ok(())
    }

    fn set_region_active(
        env: Env,
        region_id: Symbol,
        active: bool,
    ) -> Result<(), AgentRegistryError> {
        require_admin(&env)?;
        let mut region = load_region(&env, &region_id)?;
        region.active = active;
        storage::set_region(&env, &region);
        storage::bump_instance(&env);
        events::region_configured(&env, &region_id, region.min_bond, active);
        Ok(())
    }

    fn map_corridor(
        env: Env,
        corridor_id: Symbol,
        region_id: Symbol,
    ) -> Result<(), AgentRegistryError> {
        require_admin(&env)?;
        load_region(&env, &region_id)?;
        storage::set_corridor_region(&env, &corridor_id, &region_id);
        storage::bump_instance(&env);
        events::corridor_mapped(&env, &corridor_id, &region_id);
        Ok(())
    }

    fn register_agent(
        env: Env,
        agent: Address,
        region_id: Symbol,
        bond_amount: i128,
    ) -> Result<Agent, AgentRegistryError> {
        agent.require_auth();
        if bond_amount <= 0 {
            return Err(AgentRegistryError::InvalidAmount);
        }

        let region = load_region(&env, &region_id)?;
        if !region.active {
            return Err(AgentRegistryError::RegionInactive);
        }
        if !region.accepts_bond(bond_amount) {
            return Err(AgentRegistryError::BondBelowMinimum);
        }

        let bond_token = storage::get_bond_token(&env)?;
        let now = env.ledger().timestamp();

        let existing = storage::get_agent(&env, &agent);
        let is_new = existing.is_none();
        let mut record = match existing {
            // A revoked agent may start over, but only by posting a fresh bond
            // that clears the region minimum — old collateral never counts.
            Some(previous) if previous.status == AgentStatus::Revoked => Agent {
                address: agent.clone(),
                region_id: region_id.clone(),
                bond_token: bond_token.clone(),
                bond: 0,
                status: AgentStatus::Pending,
                slash_count: previous.slash_count,
                registered_at: previous.registered_at,
                updated_at: now,
            },
            Some(_) => return Err(AgentRegistryError::AgentAlreadyRegistered),
            None => Agent {
                address: agent.clone(),
                region_id: region_id.clone(),
                bond_token: bond_token.clone(),
                bond: 0,
                status: AgentStatus::Pending,
                slash_count: 0,
                registered_at: now,
                updated_at: now,
            },
        };

        if record.bond_token != bond_token {
            return Err(AgentRegistryError::BondTokenMismatch);
        }

        token::Client::new(&env, &bond_token).transfer(
            &agent,
            &env.current_contract_address(),
            &bond_amount,
        );

        record.bond = record
            .bond
            .checked_add(bond_amount)
            .ok_or(AgentRegistryError::Overflow)?;
        record.updated_at = now;

        storage::set_agent(&env, &record);
        storage::push_region_agent(&env, &region_id, &agent);

        let mut stats = storage::get_stats(&env);
        if is_new {
            stats.total_agents = stats.total_agents.saturating_add(1);
        }
        stats.total_bonded = stats
            .total_bonded
            .checked_add(bond_amount)
            .ok_or(AgentRegistryError::Overflow)?;
        storage::set_stats(&env, &stats);
        storage::bump_instance(&env);

        events::agent_registered(&env, &agent, &region_id, record.bond);
        Ok(record)
    }

    fn top_up_bond(env: Env, agent: Address, amount: i128) -> Result<i128, AgentRegistryError> {
        agent.require_auth();
        if amount <= 0 {
            return Err(AgentRegistryError::InvalidAmount);
        }

        let mut record = load_agent(&env, &agent)?;
        let bond_token = storage::get_bond_token(&env)?;
        token::Client::new(&env, &bond_token).transfer(
            &agent,
            &env.current_contract_address(),
            &amount,
        );

        record.bond = record
            .bond
            .checked_add(amount)
            .ok_or(AgentRegistryError::Overflow)?;
        record.updated_at = env.ledger().timestamp();
        storage::set_agent(&env, &record);

        let mut stats = storage::get_stats(&env);
        stats.total_bonded = stats
            .total_bonded
            .checked_add(amount)
            .ok_or(AgentRegistryError::Overflow)?;
        storage::set_stats(&env, &stats);
        storage::bump_instance(&env);

        events::bond_topped_up(&env, &agent, amount, record.bond);
        Ok(record.bond)
    }

    fn withdraw_bond(env: Env, agent: Address, amount: i128) -> Result<i128, AgentRegistryError> {
        agent.require_auth();
        if amount <= 0 {
            return Err(AgentRegistryError::InvalidAmount);
        }

        let mut record = load_agent(&env, &agent)?;
        if !record.status.bond_is_withdrawable() {
            return Err(AgentRegistryError::BondLockedWhileAuthorized);
        }
        if amount > record.bond {
            return Err(AgentRegistryError::InsufficientBond);
        }

        let bond_token = storage::get_bond_token(&env)?;
        money_out(&env, &bond_token, &agent, amount)?;

        record.bond -= amount;
        record.updated_at = env.ledger().timestamp();
        storage::set_agent(&env, &record);

        let mut stats = storage::get_stats(&env);
        stats.total_bonded -= amount;
        storage::set_stats(&env, &stats);
        storage::bump_instance(&env);

        events::bond_withdrawn(&env, &agent, amount, record.bond);
        Ok(record.bond)
    }

    fn authorize_agent(env: Env, agent: Address) -> Result<(), AgentRegistryError> {
        require_admin(&env)?;
        let mut record = load_agent(&env, &agent)?;

        if !matches!(record.status, AgentStatus::Pending | AgentStatus::Suspended) {
            return Err(AgentRegistryError::InvalidStatusTransition);
        }

        let region = load_region(&env, &record.region_id)?;
        if !region.active {
            return Err(AgentRegistryError::RegionInactive);
        }
        if !region.accepts_bond(record.bond) {
            return Err(AgentRegistryError::BondBelowMinimum);
        }
        if region.max_agents > 0 && count_authorized(&env, &record.region_id) >= region.max_agents {
            return Err(AgentRegistryError::RegionFull);
        }

        apply_transition(
            &env,
            &mut record,
            AgentStatus::Authorized,
            &Symbol::new(&env, "approved"),
        );
        storage::bump_instance(&env);
        Ok(())
    }

    fn suspend_agent(env: Env, agent: Address, reason: Symbol) -> Result<(), AgentRegistryError> {
        require_admin(&env)?;
        let mut record = load_agent(&env, &agent)?;
        if record.status == AgentStatus::Revoked {
            return Err(AgentRegistryError::InvalidStatusTransition);
        }
        apply_transition(&env, &mut record, AgentStatus::Suspended, &reason);
        storage::bump_instance(&env);
        Ok(())
    }

    fn revoke_agent(env: Env, agent: Address, reason: Symbol) -> Result<(), AgentRegistryError> {
        require_admin(&env)?;
        let mut record = load_agent(&env, &agent)?;
        if record.status == AgentStatus::Revoked {
            return Err(AgentRegistryError::InvalidStatusTransition);
        }
        apply_transition(&env, &mut record, AgentStatus::Revoked, &reason);
        storage::bump_instance(&env);
        Ok(())
    }

    fn slash_agent(
        env: Env,
        agent: Address,
        amount: i128,
        reason: Symbol,
    ) -> Result<i128, AgentRegistryError> {
        require_admin(&env)?;
        if amount <= 0 {
            return Err(AgentRegistryError::InvalidAmount);
        }

        let mut record = load_agent(&env, &agent)?;
        if amount > record.bond {
            return Err(AgentRegistryError::SlashExceedsBond);
        }

        let treasury = storage::get_treasury(&env)?;
        record.bond -= amount;
        record.slash_count = record.slash_count.saturating_add(1);

        // A slash that drops an agent below its region minimum also drops its
        // ability to settle: leaving it authorized would let an under-collateralised
        // agent keep claiming transfers until the next manual review.
        if record.status == AgentStatus::Authorized {
            let region = load_region(&env, &record.region_id)?;
            if !region.accepts_bond(record.bond) {
                apply_transition(
                    &env,
                    &mut record,
                    AgentStatus::Suspended,
                    &Symbol::new(&env, "underwater"),
                );
            }
        }

        record.updated_at = env.ledger().timestamp();
        storage::set_agent(&env, &record);

        let bond_token = storage::get_bond_token(&env)?;
        money_out(&env, &bond_token, &treasury, amount)?;

        let mut stats = storage::get_stats(&env);
        stats.total_bonded -= amount;
        stats.total_slashed = stats
            .total_slashed
            .checked_add(amount)
            .ok_or(AgentRegistryError::Overflow)?;
        storage::set_stats(&env, &stats);
        storage::bump_instance(&env);

        events::agent_slashed(&env, &agent, amount, amount, &reason);
        Ok(amount)
    }

    fn is_authorized(env: Env, agent: Address, region_id: Symbol) -> bool {
        is_authorized_in(&env, &agent, &region_id)
    }

    fn is_authorized_for_corridor(env: Env, agent: Address, corridor_id: Symbol) -> bool {
        match storage::get_corridor_region(&env, &corridor_id) {
            Some(region_id) => is_authorized_in(&env, &agent, &region_id),
            None => false,
        }
    }

    fn get_agent(env: Env, agent: Address) -> Option<Agent> {
        storage::get_agent(&env, &agent)
    }

    fn get_bond(env: Env, agent: Address) -> i128 {
        storage::get_agent(&env, &agent).map_or(0, |record| record.bond)
    }

    fn get_region(env: Env, region_id: Symbol) -> Option<RegionConfig> {
        storage::get_region(&env, &region_id)
    }

    fn list_regions(env: Env) -> Vec<Symbol> {
        storage::region_list(&env)
    }

    fn list_region_agents(env: Env, region_id: Symbol) -> Vec<Address> {
        storage::region_agents(&env, &region_id)
    }

    fn region_agent_count(env: Env, region_id: Symbol) -> u32 {
        storage::count_region_agents(&env, &region_id)
    }

    fn registry_stats(env: Env) -> RegistryStats {
        storage::get_stats(&env)
    }
}
