//! Escrow implementation.

use soroban_sdk::{contractimpl, symbol_short, token, Address, Bytes, BytesN, Env, Symbol, Vec};

use remit_interfaces::agent_registry::AgentRegistryClient;
use remit_interfaces::compliance::ComplianceHookClient;
use remit_interfaces::escrow::{
    ClaimQuote, ClaimReceipt, EscrowConfig, EscrowError, EscrowStats, EscrowInterface, Transfer,
    TransferStatus, MAX_FEE_BPS,
};

use crate::events;
use crate::storage;
// `RemitEscrowArgs` is generated by `#[contract]` in the crate root and is
// referred to by the `#[contractimpl]` macro from inside this module.
use crate::{RemitEscrow, RemitEscrowArgs, RemitEscrowClient};

/* ------------------------------------------------------------------ */
/* helpers                                                             */
/* ------------------------------------------------------------------ */

fn require_admin(env: &Env) -> Result<Address, EscrowError> {
    let admin = storage::get_admin(env)?;
    admin.require_auth();
    Ok(admin)
}

/// Platform fee in the transfer's own token.
///
/// Rounded down, in the sender's favour: the alternative quietly over-charges on
/// every transfer that does not divide evenly.
fn fee_for(amount: i128, fee_bps: u32) -> Result<i128, EscrowError> {
    amount
        .checked_mul(i128::from(fee_bps))
        .ok_or(EscrowError::Overflow)?
        .checked_div(10_000)
        .ok_or(EscrowError::Overflow)
}

fn load_config(env: &Env) -> Result<EscrowConfig, EscrowError> {
    storage::get_config(env)
}

fn load_transfer(env: &Env, id: u64) -> Result<Transfer, EscrowError> {
    storage::get_transfer(env, id).ok_or(EscrowError::TransferNotFound)
}

/// Return held funds to an address and record the outcome.
///
/// Infallible by construction: the token transfer either happens or traps the
/// whole invocation, so there is no partial state for the caller to handle.
fn release(env: &Env, transfer: &mut Transfer, to: &Address, next_status: TransferStatus) {
    token::Client::new(env, &transfer.token).transfer(
        &env.current_contract_address(),
        to,
        &transfer.amount,
    );
    transfer.status = next_status;
    transfer.settled_at = env.ledger().timestamp();
    storage::set_transfer(env, transfer);
}

/// Ask the compliance gate whether this transfer may proceed.
///
/// The two failure shapes are kept apart on purpose: a typed refusal from the
/// gate is a policy outcome the sender can act on, whereas an invocation that
/// could not complete is an incident. Collapsing them into one error would make
/// the API report "you need to verify your ID" during a hook outage.
fn check_compliance(
    env: &Env,
    hook: &Address,
    sender: &Address,
    amount: i128,
    corridor_id: &Symbol,
) -> Result<(), EscrowError> {
    let outcome = ComplianceHookClient::new(env, hook).try_check_transfer_allowed(
        sender,
        &amount,
        corridor_id,
    );
    match outcome {
        Ok(Ok(true)) => Ok(()),
        // A policy outcome the sender can act on. `Ok(false)` is reserved by the
        // gate for a future "needs manual review" state and is treated as a
        // refusal rather than silently allowed; `Err(Ok(..))` is one of the
        // gate's typed refusals.
        Ok(Ok(false)) | Err(Ok(_)) => Err(EscrowError::ComplianceRefused),
        // An incident: the reply could not be decoded, or the invocation never
        // completed (bad address, budget exhausted, host error).
        Ok(Err(_)) | Err(Err(_)) => Err(EscrowError::ComplianceCallFailed),
    }
}

/// Record the transfer against the sender's rolling daily volume.
fn commit_volume(
    env: &Env,
    hook: &Address,
    sender: &Address,
    amount: i128,
    corridor_id: &Symbol,
) -> Result<(), EscrowError> {
    let outcome =
        ComplianceHookClient::new(env, hook).try_commit_transfer(sender, &amount, corridor_id);
    match outcome {
        Ok(Ok(_)) => Ok(()),
        Err(Ok(_)) => Err(EscrowError::ComplianceRefused),
        Ok(Err(_)) | Err(Err(_)) => Err(EscrowError::ComplianceCallFailed),
    }
}

/// Confirm the claimant may settle in this corridor.
fn check_agent(
    env: &Env,
    registry: &Address,
    agent: &Address,
    corridor_id: &Symbol,
) -> Result<(), EscrowError> {
    let outcome = AgentRegistryClient::new(env, registry)
        .try_is_authorized_for_corridor(agent, corridor_id);
    match outcome {
        Ok(Ok(true)) => Ok(()),
        Ok(Ok(false)) => Err(EscrowError::AgentNotAuthorized),
        // Cannot decode the answer, or the registry rejected the call outright.
        // Either way we cannot prove authorization, so fail closed.
        Ok(Err(_)) | Err(_) => Err(EscrowError::RegistryCallFailed),
    }
}

/* ------------------------------------------------------------------ */
/* contract                                                            */
/* ------------------------------------------------------------------ */

#[contractimpl]
impl EscrowInterface for RemitEscrow {
    fn initialize(
        env: Env,
        admin: Address,
        agent_registry: Address,
        compliance_hook: Address,
        treasury: Address,
        fee_bps: u32,
        max_expiry_secs: u64,
    ) -> Result<(), EscrowError> {
        if storage::has_admin(&env) {
            return Err(EscrowError::AlreadyInitialized);
        }
        if fee_bps > MAX_FEE_BPS || max_expiry_secs == 0 {
            return Err(EscrowError::InvalidConfig);
        }
        admin.require_auth();

        storage::set_admin(&env, &admin);
        storage::set_config(
            &env,
            &EscrowConfig {
                agent_registry,
                compliance_hook,
                treasury,
                fee_bps,
                paused: false,
                max_expiry_secs,
            },
        );
        storage::set_stats(&env, &EscrowStats::default());
        storage::bump_instance(&env);
        Ok(())
    }

    fn set_admin(env: Env, new_admin: Address) -> Result<(), EscrowError> {
        let previous = require_admin(&env)?;
        storage::set_admin(&env, &new_admin);
        storage::bump_instance(&env);
        events::admin_changed(&env, &previous, &new_admin);
        Ok(())
    }

    fn set_fee_bps(env: Env, fee_bps: u32) -> Result<(), EscrowError> {
        require_admin(&env)?;
        if fee_bps > MAX_FEE_BPS {
            return Err(EscrowError::FeeTooHigh);
        }
        let mut config = load_config(&env)?;
        config.fee_bps = fee_bps;
        storage::set_config(&env, &config);
        storage::bump_instance(&env);
        events::config_updated(
            &env,
            &symbol_short!("fee"),
            fee_bps,
            config.paused,
            config.max_expiry_secs,
        );
        Ok(())
    }

    fn set_treasury(env: Env, treasury: Address) -> Result<(), EscrowError> {
        require_admin(&env)?;
        let mut config = load_config(&env)?;
        config.treasury = treasury.clone();
        storage::set_config(&env, &config);
        storage::bump_instance(&env);
        events::wiring_updated(&env, &symbol_short!("tresry"), &treasury);
        Ok(())
    }

    fn set_agent_registry(env: Env, agent_registry: Address) -> Result<(), EscrowError> {
        require_admin(&env)?;
        let mut config = load_config(&env)?;
        config.agent_registry = agent_registry.clone();
        storage::set_config(&env, &config);
        storage::bump_instance(&env);
        events::wiring_updated(&env, &symbol_short!("registry"), &agent_registry);
        Ok(())
    }

    fn set_compliance_hook(env: Env, compliance_hook: Address) -> Result<(), EscrowError> {
        require_admin(&env)?;
        let mut config = load_config(&env)?;
        config.compliance_hook = compliance_hook.clone();
        storage::set_config(&env, &config);
        storage::bump_instance(&env);
        events::wiring_updated(&env, &symbol_short!("hook"), &compliance_hook);
        Ok(())
    }

    fn set_max_expiry(env: Env, max_expiry_secs: u64) -> Result<(), EscrowError> {
        require_admin(&env)?;
        if max_expiry_secs == 0 {
            return Err(EscrowError::InvalidConfig);
        }
        let mut config = load_config(&env)?;
        config.max_expiry_secs = max_expiry_secs;
        storage::set_config(&env, &config);
        storage::bump_instance(&env);
        events::config_updated(
            &env,
            &symbol_short!("expiry"),
            config.fee_bps,
            config.paused,
            max_expiry_secs,
        );
        Ok(())
    }

    fn set_paused(env: Env, paused: bool) -> Result<(), EscrowError> {
        require_admin(&env)?;
        let mut config = load_config(&env)?;
        config.paused = paused;
        storage::set_config(&env, &config);
        storage::bump_instance(&env);
        events::config_updated(
            &env,
            &symbol_short!("paused"),
            config.fee_bps,
            paused,
            config.max_expiry_secs,
        );
        Ok(())
    }

    fn create_transfer(
        env: Env,
        sender: Address,
        amount: i128,
        token: Address,
        claim_hash: BytesN<32>,
        corridor_id: Symbol,
        expiry: u64,
    ) -> Result<u64, EscrowError> {
        sender.require_auth();

        let config = load_config(&env)?;
        if config.paused {
            return Err(EscrowError::Paused);
        }
        if amount <= 0 {
            return Err(EscrowError::InvalidAmount);
        }

        let now = env.ledger().timestamp();
        if expiry <= now {
            return Err(EscrowError::InvalidExpiry);
        }
        if expiry - now > config.max_expiry_secs {
            return Err(EscrowError::ExpiryTooFar);
        }

        // Compliance runs *before* any funds move. A rejected transfer should
        // never touch a balance, not even momentarily — a lock-then-refund path
        // would burn gas and leak intent to observers for no benefit.
        check_compliance(&env, &config.compliance_hook, &sender, amount, &corridor_id)?;

        token::Client::new(&env, &token).transfer(
            &sender,
            &env.current_contract_address(),
            &amount,
        );

        // Per-transfer checks are not enough on their own: the daily ceiling is
        // cumulative, so it is committed here, inside the same transaction, and
        // reverts the whole transfer if it would breach.
        commit_volume(&env, &config.compliance_hook, &sender, amount, &corridor_id)?;

        let id = storage::next_id(&env);
        let transfer = Transfer {
            id,
            sender: sender.clone(),
            amount,
            token: token.clone(),
            claim_hash: claim_hash.clone(),
            corridor_id: corridor_id.clone(),
            expiry,
            status: TransferStatus::Pending,
            created_at: now,
            settled_at: 0,
            claimed_by: None,
        };
        storage::set_transfer(&env, &transfer);
        storage::push_sender_transfer(&env, &sender, id);

        let mut stats = storage::get_stats(&env);
        stats.created = stats.created.saturating_add(1);
        stats.volume_locked = stats
            .volume_locked
            .checked_add(amount)
            .ok_or(EscrowError::Overflow)?;
        storage::set_stats(&env, &stats);
        storage::bump_instance(&env);

        events::transfer_created(
            &env,
            id,
            &sender,
            amount,
            &token,
            &corridor_id,
            &claim_hash,
            expiry,
        );
        Ok(id)
    }

    fn cancel_transfer(env: Env, sender: Address, transfer_id: u64) -> Result<(), EscrowError> {
        sender.require_auth();
        let mut transfer = load_transfer(&env, transfer_id)?;

        if transfer.sender != sender {
            return Err(EscrowError::Unauthorized);
        }
        if !transfer.is_pending() {
            return Err(EscrowError::TransferNotPending);
        }

        // Note the race this leaves open, documented rather than hidden: a sender
        // who has already handed the code to a recipient can cancel while the
        // agent is counting out cash, and the agent's later claim then fails.
        // The mitigation is procedural and is enforced by the agent app, which
        // re-reads the transfer status immediately before releasing cash — the
        // same pattern as a card terminal re-authorising at the counter.
        let sender = transfer.sender.clone();
        release(&env, &mut transfer, &sender, TransferStatus::Cancelled);

        let mut stats = storage::get_stats(&env);
        stats.cancelled = stats.cancelled.saturating_add(1);
        stats.volume_locked -= transfer.amount;
        storage::set_stats(&env, &stats);
        storage::bump_instance(&env);

        events::transfer_cancelled(
            &env,
            transfer_id,
            &transfer.sender,
            transfer.amount,
            &transfer.corridor_id,
        );
        Ok(())
    }

    fn claim_transfer(
        env: Env,
        agent: Address,
        transfer_id: u64,
        reveal: BytesN<32>,
    ) -> Result<ClaimReceipt, EscrowError> {
        agent.require_auth();

        let config = load_config(&env)?;
        let mut transfer = load_transfer(&env, transfer_id)?;

        if !transfer.is_pending() {
            return Err(EscrowError::TransferNotPending);
        }
        let now = env.ledger().timestamp();
        if transfer.has_expired(now) {
            return Err(EscrowError::TransferExpired);
        }
        if transfer.sender == agent {
            return Err(EscrowError::SenderCannotClaim);
        }

        // Commit-reveal verification. The hash comparison is the only thing
        // standing between a claim code and the funds, so it happens before the
        // (more expensive) cross-contract registry call.
        let computed: BytesN<32> = env
            .crypto()
            .sha256(&Bytes::from_array(&env, &reveal.to_array()))
            .into();
        if computed != transfer.claim_hash {
            return Err(EscrowError::InvalidClaimCode);
        }

        check_agent(
            &env,
            &config.agent_registry,
            &agent,
            &transfer.corridor_id,
        )?;

        let fee = fee_for(transfer.amount, config.fee_bps)?;
        let payout = transfer.amount - fee;
        let token_client = token::Client::new(&env, &transfer.token);
        token_client.transfer(&env.current_contract_address(), &agent, &payout);
        if fee > 0 {
            token_client.transfer(&env.current_contract_address(), &config.treasury, &fee);
        }

        transfer.status = TransferStatus::Claimed;
        transfer.settled_at = now;
        transfer.claimed_by = Some(agent.clone());
        storage::set_transfer(&env, &transfer);

        let mut stats = storage::get_stats(&env);
        stats.claimed = stats.claimed.saturating_add(1);
        stats.volume_locked -= transfer.amount;
        stats.volume_settled = stats
            .volume_settled
            .checked_add(transfer.amount)
            .ok_or(EscrowError::Overflow)?;
        stats.fees_collected = stats
            .fees_collected
            .checked_add(fee)
            .ok_or(EscrowError::Overflow)?;
        storage::set_stats(&env, &stats);
        storage::bump_instance(&env);

        events::transfer_claimed(
            &env,
            transfer_id,
            &agent,
            &transfer.corridor_id,
            transfer.amount,
            fee,
            payout,
        );

        Ok(ClaimReceipt {
            transfer_id,
            agent,
            gross: transfer.amount,
            fee,
            payout,
            settled_at: now,
        })
    }

    fn refund_expired(env: Env, transfer_id: u64) -> Result<(), EscrowError> {
        let mut transfer = load_transfer(&env, transfer_id)?;

        if !transfer.is_pending() {
            return Err(EscrowError::TransferNotPending);
        }
        if !transfer.has_expired(env.ledger().timestamp()) {
            return Err(EscrowError::TransferNotExpired);
        }

        // Deliberately unauthenticated: the sender may have abandoned the
        // transfer or lost their key, and the alternative to letting anyone
        // trigger the refund is funds locked in escrow forever. The destination
        // is the address recorded at creation, so a third party can only *help*,
        // never redirect.
        let sender = transfer.sender.clone();
        release(&env, &mut transfer, &sender, TransferStatus::Refunded);

        let mut stats = storage::get_stats(&env);
        stats.refunded = stats.refunded.saturating_add(1);
        stats.volume_locked -= transfer.amount;
        storage::set_stats(&env, &stats);
        storage::bump_instance(&env);

        events::transfer_refunded(&env, transfer_id, &sender, transfer.amount, &transfer.corridor_id);
        Ok(())
    }

    fn get_transfer(env: Env, transfer_id: u64) -> Option<Transfer> {
        storage::get_transfer(&env, transfer_id)
    }

    fn transfer_count(env: Env) -> u64 {
        storage::transfer_count(&env)
    }

    fn list_sender_transfers(env: Env, sender: Address) -> Vec<u64> {
        storage::sender_transfers(&env, &sender)
    }

    fn escrow_config(env: Env) -> Option<EscrowConfig> {
        storage::get_config(&env).ok()
    }

    fn escrow_stats(env: Env) -> EscrowStats {
        storage::get_stats(&env)
    }

    fn quote_claim(env: Env, transfer_id: u64) -> Result<ClaimQuote, EscrowError> {
        let config = load_config(&env)?;
        let transfer = load_transfer(&env, transfer_id)?;
        if !transfer.is_pending() {
            return Err(EscrowError::TransferNotPending);
        }

        let fee = fee_for(transfer.amount, config.fee_bps)?;
        Ok(ClaimQuote {
            transfer_id,
            gross: transfer.amount,
            fee,
            payout: transfer.amount - fee,
        })
    }
}
