//! Compliance hook implementation.
//!
//! The decision logic lives in `evaluate`, a pure-ish function that reads state
//! and returns either the resolved tiers or the exact rule that refused the
//! transfer. Both the boolean gate and the UI-facing explanation are thin
//! projections of it, which is what keeps "what the app said" and "what the
//! contract enforced" from diverging.

use soroban_sdk::{contractimpl, symbol_short, Address, BytesN, Env, Symbol, Vec};

use crate::errors::ComplianceError;
use crate::events;
use crate::storage;
use crate::types::{Attestation, ComplianceStats, KycTier, TierThresholds, TransferDecision};
// Generated by `#[contract]` in the crate root; the `#[contractimpl]` macro
// below refers to them from inside this module.
use crate::{ComplianceHook, ComplianceHookArgs, ComplianceHookClient, ComplianceHookInterface};

/// Resolved outcome of a successful evaluation.
struct Evaluation {
    required_tier: KycTier,
    held_tier: KycTier,
    remaining_daily: i128,
    /// The sender's volume for this day *including* this transfer.
    ///
    /// Carried out of the evaluation so the write path does not have to read the
    /// same bucket a second time: the ceiling check and the increment are then
    /// guaranteed to be reading one value rather than two.
    daily_total_after: i128,
}

fn require_admin(env: &Env) -> Result<Address, ComplianceError> {
    let admin = storage::get_admin(env)?;
    admin.require_auth();
    Ok(admin)
}

/// Machine-readable tag for a refusal, so the same vocabulary is used in events,
/// API responses and the admin console.
fn reason_tag(error: ComplianceError) -> Symbol {
    match error {
        ComplianceError::NotInitialized => symbol_short!("no_init"),
        ComplianceError::AlreadyInitialized => symbol_short!("inited"),
        ComplianceError::Unauthorized => symbol_short!("unauth"),
        ComplianceError::NotAnAttester => symbol_short!("no_attest"),
        ComplianceError::NotEscrow => symbol_short!("not_escr"),
        ComplianceError::InvalidAmount => symbol_short!("bad_amt"),
        ComplianceError::UnknownCorridor => symbol_short!("no_corr"),
        ComplianceError::InvalidThresholds => symbol_short!("bad_tier"),
        ComplianceError::TransfersPaused => symbol_short!("paused"),
        ComplianceError::AttestationMissing => symbol_short!("kyc_need"),
        ComplianceError::AttestationExpired => symbol_short!("kyc_exp"),
        ComplianceError::AttestationRevoked => symbol_short!("kyc_rev"),
        ComplianceError::TierTooLow => symbol_short!("tier_low"),
        ComplianceError::DailyLimitExceeded => symbol_short!("daily_cap"),
        ComplianceError::InvalidExpiry => symbol_short!("exp_bad"),
        ComplianceError::Overflow => symbol_short!("overflow"),
        ComplianceError::EscrowNotSet => symbol_short!("no_escr"),
    }
}

/// The single source of truth for "may this transfer proceed?".
fn evaluate(
    env: &Env,
    sender: &Address,
    amount: i128,
    corridor_id: &Symbol,
) -> Result<Evaluation, ComplianceError> {
    if storage::is_paused(env) {
        return Err(ComplianceError::TransfersPaused);
    }
    if amount <= 0 {
        return Err(ComplianceError::InvalidAmount);
    }

    let thresholds =
        storage::get_thresholds(env, corridor_id).ok_or(ComplianceError::UnknownCorridor)?;
    let required_tier = thresholds.required_tier(amount);

    let now = env.ledger().timestamp();
    let day = storage::day_of(now);
    let spent = storage::daily_volume(env, sender, corridor_id, day);
    let headroom = spent.checked_add(amount).ok_or(ComplianceError::Overflow)?;
    if headroom > thresholds.daily_limit {
        return Err(ComplianceError::DailyLimitExceeded);
    }
    let remaining_daily = thresholds.daily_limit - headroom;

    let attestation = storage::get_attestation(env, sender);

    // A *revoked* attestation is a sanctions/fraud signal, so it blocks even a
    // transfer small enough that no verification would normally be required.
    // An absent or merely expired one does not: a first-time sender making a
    // small transfer is exactly who this network exists to serve.
    if let Some(record) = &attestation {
        if record.revoked {
            return Err(ComplianceError::AttestationRevoked);
        }
    }

    let held_tier = if required_tier == KycTier::None {
        attestation.as_ref().map_or(KycTier::None, |r| r.tier)
    } else {
        let record = attestation
            .as_ref()
            .ok_or(ComplianceError::AttestationMissing)?;
        if record.expires_at <= now {
            return Err(ComplianceError::AttestationExpired);
        }
        if !record.tier.satisfies(required_tier) {
            return Err(ComplianceError::TierTooLow);
        }
        record.tier
    };

    Ok(Evaluation {
        required_tier,
        held_tier,
        daily_total_after: headroom,
        remaining_daily,
    })
}

/* ------------------------------------------------------------------ */
/* contract                                                            */
/* ------------------------------------------------------------------ */

#[contractimpl]
impl ComplianceHookInterface for ComplianceHook {
    fn initialize(env: Env, admin: Address) -> Result<(), ComplianceError> {
        if storage::has_admin(&env) {
            return Err(ComplianceError::AlreadyInitialized);
        }
        admin.require_auth();
        storage::set_admin(&env, &admin);
        storage::set_paused(&env, false);
        storage::set_stats(&env, &ComplianceStats::default());
        storage::bump_instance(&env);
        Ok(())
    }

    fn set_operator(env: Env, operator: Address, allowed: bool) -> Result<(), ComplianceError> {
        require_admin(&env)?;
        storage::set_operator(&env, &operator, allowed);
        storage::bump_instance(&env);
        events::operator_updated(&env, &operator, allowed);
        Ok(())
    }

    fn set_escrow(env: Env, escrow: Address) -> Result<(), ComplianceError> {
        require_admin(&env)?;
        storage::set_escrow(&env, &escrow);
        storage::bump_instance(&env);
        events::escrow_updated(&env, &escrow);
        Ok(())
    }

    fn set_paused(env: Env, paused: bool) -> Result<(), ComplianceError> {
        require_admin(&env)?;
        storage::set_paused(&env, paused);
        storage::bump_instance(&env);
        events::pause_changed(&env, paused);
        Ok(())
    }

    fn set_tier_thresholds(env: Env, thresholds: TierThresholds) -> Result<(), ComplianceError> {
        require_admin(&env)?;
        if !thresholds.is_valid() {
            return Err(ComplianceError::InvalidThresholds);
        }

        storage::set_thresholds(&env, &thresholds);
        storage::push_corridor(&env, &thresholds.corridor_id);
        storage::bump_instance(&env);
        events::thresholds_updated(&env, &thresholds.corridor_id, &thresholds);
        Ok(())
    }

    fn get_tier_thresholds(env: Env, corridor_id: Symbol) -> Option<TierThresholds> {
        storage::get_thresholds(&env, &corridor_id)
    }

    fn list_corridors(env: Env) -> Vec<Symbol> {
        storage::corridor_list(&env)
    }

    fn publish_attestation(
        env: Env,
        attester: Address,
        subject: Address,
        tier: KycTier,
        attestation_hash: BytesN<32>,
        region_id: Symbol,
        provider_id: Symbol,
        expires_at: u64,
    ) -> Result<(), ComplianceError> {
        attester.require_auth();
        if !storage::is_operator(&env, &attester) {
            return Err(ComplianceError::NotAnAttester);
        }

        let now = env.ledger().timestamp();
        if expires_at <= now {
            return Err(ComplianceError::InvalidExpiry);
        }

        let previous_was_live =
            storage::get_attestation(&env, &subject).is_some_and(|record| record.is_live(now));

        let record = Attestation {
            subject: subject.clone(),
            tier,
            attestation_hash: attestation_hash.clone(),
            region_id,
            provider_id: provider_id.clone(),
            issued_at: now,
            expires_at,
            revoked: false,
        };
        storage::set_attestation(&env, &record);

        let mut stats = storage::get_stats(&env);
        if !previous_was_live {
            stats.attestations_issued = stats.attestations_issued.saturating_add(1);
        }
        storage::set_stats(&env, &stats);
        storage::bump_instance(&env);

        events::attestation_published(
            &env,
            &subject,
            tier,
            &attestation_hash,
            &provider_id,
            expires_at,
        );
        Ok(())
    }

    fn revoke_attestation(
        env: Env,
        attester: Address,
        subject: Address,
        reason: Symbol,
    ) -> Result<(), ComplianceError> {
        attester.require_auth();
        if !storage::is_operator(&env, &attester) {
            return Err(ComplianceError::NotAnAttester);
        }

        let mut record =
            storage::get_attestation(&env, &subject).ok_or(ComplianceError::AttestationMissing)?;
        // Idempotent: a second revocation for the same subject is a no-op rather
        // than an error, because revocation often arrives from a retrying
        // screening webhook.
        if !record.revoked {
            record.revoked = true;
            storage::set_attestation(&env, &record);

            let mut stats = storage::get_stats(&env);
            stats.attestations_revoked = stats.attestations_revoked.saturating_add(1);
            storage::set_stats(&env, &stats);

            events::attestation_revoked(&env, &subject, &reason);
        }
        storage::bump_instance(&env);
        Ok(())
    }

    fn get_attestation(env: Env, subject: Address) -> Option<Attestation> {
        storage::get_attestation(&env, &subject)
    }

    fn check_transfer_allowed(
        env: Env,
        sender: Address,
        amount: i128,
        corridor_id: Symbol,
    ) -> Result<bool, ComplianceError> {
        evaluate(&env, &sender, amount, &corridor_id).map(|_| true)
    }

    fn explain_transfer(
        env: Env,
        sender: Address,
        amount: i128,
        corridor_id: Symbol,
    ) -> TransferDecision {
        let required_tier = storage::get_thresholds(&env, &corridor_id)
            .map_or(KycTier::None, |t| t.required_tier(amount));
        let held_tier = storage::get_attestation(&env, &sender).map_or(KycTier::None, |a| a.tier);

        match evaluate(&env, &sender, amount, &corridor_id) {
            Ok(evaluation) => TransferDecision {
                allowed: true,
                required_tier: evaluation.required_tier,
                held_tier: evaluation.held_tier,
                reason: symbol_short!("ok"),
                remaining_daily: evaluation.remaining_daily,
            },
            Err(error) => TransferDecision {
                allowed: false,
                required_tier,
                held_tier,
                reason: reason_tag(error),
                remaining_daily: 0,
            },
        }
    }

    fn commit_transfer(
        env: Env,
        sender: Address,
        amount: i128,
        corridor_id: Symbol,
    ) -> Result<i128, ComplianceError> {
        // Only the registered escrow may commit volume. It is the contract that
        // verified the sender's authorization for this specific transfer, and
        // this call now *enforces* the gate as well as recording the volume — so
        // the escrow-only check here is what stops the gate being bypassed by a
        // sender committing their own volume with a favourable amount.
        //
        // A contract address authorizes implicitly when it is the direct
        // invoker of the call, so `require_auth` here is satisfied only by the
        // escrow reaching in — not by a sender trying to burn their own limit.
        let escrow = storage::get_escrow(&env)?;
        escrow.require_auth();
        if amount <= 0 {
            return Err(ComplianceError::InvalidAmount);
        }

        // One enforcing write path. The gate and the commit used to be two
        // separate entry points, which cost every transfer a second
        // cross-contract invocation and a second read of the thresholds and the
        // day's volume — and required the ceiling to be restated here so that a
        // caller could not commit without having checked. Evaluating inside the
        // write path removes both the duplication and the cost: the check and
        // the increment cannot disagree, because they read one value once.
        //
        // `check_transfer_allowed` and `explain_transfer` remain as read-only
        // projections of the same rule, for callers that want an answer without
        // writing (the API preflights a quote this way).
        let evaluation = evaluate(&env, &sender, amount, &corridor_id)?;
        let day = storage::day_of(env.ledger().timestamp());
        let new_total = storage::set_daily_volume(
            &env,
            &sender,
            &corridor_id,
            day,
            evaluation.daily_total_after,
        );

        let mut stats = storage::get_stats(&env);
        stats.transfers_committed = stats.transfers_committed.saturating_add(1);
        if evaluation.required_tier == KycTier::Enhanced {
            stats.enhanced_tier_transfers = stats.enhanced_tier_transfers.saturating_add(1);
        }
        storage::set_stats(&env, &stats);
        storage::bump_instance(&env);

        events::transfer_committed(
            &env,
            &sender,
            &corridor_id,
            amount,
            evaluation.required_tier,
            new_total,
        );
        Ok(new_total)
    }

    fn daily_volume(env: Env, sender: Address, corridor_id: Symbol, day: u64) -> i128 {
        storage::daily_volume(&env, &sender, &corridor_id, day)
    }

    fn compliance_stats(env: Env) -> ComplianceStats {
        storage::get_stats(&env)
    }
}
